services:
  headscale:
    container_name: headscale
    image: headscale/headscale:0.26.0
    restart: unless-stopped
    ports:
      - 8080:8080
      - "127.0.0.1:9090:9090"
    volumes:
      - ./container-config:/etc/headscale
      - ./container-data:/var/lib/headscale
    entrypoint: headscale serve
    networks:
      reverseproxy-nw:

  headscale-admin:
    container_name: headscale-admin
    image: goodieshq/headscale-admin:latest
    restart: unless-stopped
    networks:
      reverseproxy-nw:

networks:   
  reverseproxy-nw:
    external: true  